### ISSUE TITLE
lights

### ISSUE THREAD

**Issue by plasticfist** [cryptk/haomnilogic-local#85] opened 2024-02-14 03:20 UTC
Connected to IP, everything except the lights seem to be working, at a glance. 
In integrations there is one entity with a light bulb icon in the card, but after adding the card to HA it that doesn't work.

light.omnilogic_pool_pool_lights
This entity is unavailable.

Notes: 
- new pool (latest omnilogic software)
- has fixed IP on same network as HA
- pool has four ColorLogic rgb lights

---
turned on debug, see the following error in log (mulltiple times)

2024-02-13 22:34:09.497 DEBUG (MainThread) [custom_components.omnilogic_local.coordinator] Finished fetching OmniLogic data in 0.204 seconds (success: True)
2024-02-13 22:34:09.512 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/**omnilogic_local**/entity.py", line 47, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1129, in state_attributes
    self.__validate_color_mode(color_mode, legacy_supported_color_modes, effect)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1093, in __validate_color_mode
    effect_color_modes = supported_color_modes | {ColorMode.ONOFF}
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'list' and 'set'

**Comment by plasticfist** [comment] 2024-02-14 16:07
This morning, now the light functionality partially works?  (no idea why an overnight pause helped).   Now I can click on the light entity in the card, and a secondary window overlay displays now, this UI looks like it contains the functionality that was missing yesterday.  It is only partially functional.  I find that I can turn the lights on, set the brightness, and change the effect, but with every click it shows an error of "Failed to call service light/turn_on. unsupported operand type(s) for |: 'list' and 'set'" in the bottom left corner on HA web UI.  Also, some (or all) of the status is not updating, the light shows as off, so I couldn't turn the light off.  

NOTE: The filter pump functionality works flawlessly in my testing.

**Comment by mikesalz** [comment] 2024-02-16 16:12
@plasticfist I have the same issue.  I actually posted another issue before I noticed you posted as well.  I am almost certain the issue is caused by this change in HA - https://developers.home-assistant.io/blog/2024/01/23/light-color-mode-changes/

I rolled back to 2024.1.6 this morning and my OmniLogic lights are now working.

**Comment by toddhutch** [comment] 2024-02-17 15:18
It does look like the HA update impacted this - debugging
2024-02-17 09:10:19.442 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546871220160] unsupported operand type(s) for |: 'list' and 'set'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/omnilogic_local/switch.py", line 122, in async_turn_on
    self.set_telemetry({"state": self.telem_value_state.ON})
  File "/config/custom_components/omnilogic_local/entity.py", line 89, in set_telemetry
    self.coordinator.async_set_updated_data(self.coordinator.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 439, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/omnilogic_local/entity.py", line 47, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1129, in state_attributes
    self.__validate_color_mode(color_mode, legacy_supported_color_modes, effect)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1093, in __validate_color_mode
    effect_color_modes = supported_color_modes | {ColorMode.ONOFF}
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'list' and 'set'

**Comment by cryptk** [comment] 2024-02-18 17:28
@plasticfist @toddhutch should fixed with 0.7.1 of the integration

**Closed by cryptk** 2024-02-18 17:28 UTC

**Comment by plasticfist** [comment] 2024-02-18 22:32
@cryptk I can confirm fix is good.  Working now for me. Thank you.

**Comment by toddhutch** [comment] 2024-02-24 14:09
@cryptk I can confirm fix is good. Working now for me. Thank you.
